### ISSUE TITLE
Weather platform/domain support

### ISSUE THREAD

**Issue by robert-alfaro** [briis/smartweatherudp#45]
Any chance this integration can get some of the love from the cloud version of this integration, specifically HA support for weather platform/domain?

**Comment by natekspencer** [comment]
So I looked at doing this, but the problem is that the weather platform requires a [condition](https://developers.home-assistant.io/docs/core/entity/weather#recommended-values-for-state-and-condition) which isn't available locally. I could calculate a condition based on a number of factors, but haven't dove into that yet. Another benefit of the weather platform is forecast data, but again, that is not available unless a call to the cloud is done, which this integration is specifically avoiding.

Is there a specific use case you need the weather platform for?

**Comment by robert-alfaro** [comment]
Thanks for explaining the underlying details.  At first glance it appeared to me an integration supporting the weather platform can use a weather card "for free". Here, it's looking like more of a custom job hooking things up on the card-side.  Have you any suggestions or examples for a weather card?

**Comment by robert-alfaro** [comment]
After looking around, I see the suggestion for using Weather template (as the weatherflow2mqtt readme describes) [Creating a Home Assistant Weather Entity](https://github.com/briis/hass-weatherflow2mqtt#creating-a-home-assistant-weather-entity)
