### ISSUE TITLE
Why is the "Feels Like" Temp no longer available?

### ISSUE THREAD

**Issue by danbutter** [briis/smartweatherudp#53]
I had been using the original custom component for a long time and didn't even realize it was moved to an integration.
After I updated from 2022.6 to 2022.7 my temps were suddenly in Celsius and when I tried to figure out why I found this.
I added this to my system and now other than the actual temp the only other thing exposed is the wet bulb temp which isn't the same as the feels like.

Any chance the Feel Like can be brought back?

thanks

**Comment by natekspencer** [comment]
This does exist, but for Tempest devices only at the moment since it requires information about temperature and humidity (air/tempest devices) and wind (sky/tempest devices). For systems that have a single Air+Sky, it should be fairly simple to implement, but which device should it belong to: the air, the sky, the hub, all of them, or something else? And in setups with multiple air and/or sky, are they somehow tied together or which one takes precedence? I haven't been able to answer these questions since my setup is just a Tempest device. I'm happy to hear others thoughts and then implement logic accordingly.

What is your system setup and how many of each device?

**Comment by danbutter** [comment]
I have the original Air and Sky and of course hub. Just one of each.
Since the entities used to be fairly simple like sensor.smartweatherudp_temperature  I don't know where you would want it grouped, but I would think it could be added to the air just to group the temp and feels like temp.
I guess I don't care what they are called as long as I can tell what is what to be able to add them to my dashboards and automations.
I really appreciate you keeping the local UDP integration alive.
Thanks

**Comment by natekspencer** [comment]
> but I would think it could be added to the air just to group the temp and feels like temp

That makes a lot of sense

> I really appreciate you keeping the local UDP integration alive

I'm glad you've been enjoying being able to utilize it!

**Comment by danbutter** [comment]
Any chance this is still being worked on?  It is that time of year where the "feels like" is very useful.

thx
